title: Dictu
description: >-
  Dictu is a very small and simple dynamically typed programming language.

color_scheme: "dictu" # Custom theme
logo: "/assets/images/dictu-logo/dictu-wordmark.svg"

version: "0.14.0"
github_username:  dictu-lang
search_enabled: true

url: "https://dictu-lang.com"
# theme: "just-the-docs"
footer_content: "This site uses Just The Docs, with modifications."

ga_tracking: "UA-109828853-2"

aux_links:
  "Contribute on GitHub":
    - "//github.com/dictu-lang/Dictu"

# Don't touch anything beyond this point

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
